
  - name: Creating a group and user for Prometheus
    shell: |
      sudo groupadd --system prometheus
      sudo useradd -s /sbin/nologin --system -g prometheus prometheus

  - name: Creating a directory
    shell: |
      sudo mkdir var/lib/prometheus
      for i in rules rules.d files_sd; do sudo mkdir -p /etc/prometheus/${i}; done

  - name: Installing curl
    dnf:
      name:
        - curl
      state: latest

  - name: Installing Prometheus
    unarchive:
      src: https://github.com/prometheus/prometheus/releases/download/v2.39.1/prometheus-2.39.1.linux-amd64.tar.gz
      dest: /usr/local/bin/
      remote_src: yes
      mode: 0755
      owner: root
      group: root

  - name: Moving Prometheus to configuration template
    copy:
      src: prom.yml
      dest: /etc/prometheus/prom.yml
      owner: root
      group: root
      mode: 0755
  
  - name: Moving the Prometheus systemd Service unit file
    copy:
      src: prom_cent.service
      dest: /etc/systemd/system/prom_cent.service
      owner: root
      group: root
      mode: 0755

  - name: Starting/Restarting Prometheus
    service:
      name: prometheus
      state: restarted
      enabled: true

  - name: Opening the port 9090 on the firewall
    shell: |
      sudo firewall-cmd --add-port=9090/tcp --permanent
      sudo firewall-cmd --reload
